### ISSUE TITLE
Fields missing in datamart predictor data

### ISSUE THREAD

**Issue by operdeck** [pegasystems/pega-datascientist-tools#127]
### pdstools version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/pdstools/) of pdstools.

### Issue description

Datamart.predictorData has the following properties

['BinResponseCount',
 'SnapshotTime',
 'BinPositives',
 'BinSymbol',
 'Type',
 'Performance',
 'ResponseCount',
 'Positives',
 'PredictorName',
 'BinIndex',
 'ModelID',
 'BinType',
 'EntryType',
 'Contents',
 'BinNegatives',
 'BinPropensity',
 'BinAdjustedPropensity',
 'PredictorCategory']

I'm missing **Negatives**, **Lift** etc but I can infer those trivially. Let's add back a few:

- **FeatureImportance** as this will be filled by ADM with feature importance - at least for AGB hopefully some day for NB as well
- **GroupIndex** important to be able to show the correlation groups
- **BinUpperBound** and **BinLowerBound** as they are helpful to re-format the labels; the default ones from Pega are not always good

### Reproducible example

```Python
---
```

### Expected behavior

---

### Installed versions

<details>

```
Replace this line with the output of pdstools.show_versions(), leave the backticks in place
```

</details>

**Comment by StijnKas** [comment]
At this point, I've not filtered out _any_ fields in https://github.com/pegasystems/pega-datascientist-tools/pull/260 - arguing that for plots I'm subsetting fields whenever I need them, and since all queries are lazy anyway, this would provide very little overhead. 

I know you want to filter out pyModelData @operdeck, we could do that. Otherwise, do you agree we could just leave every field in the query plan and use filters before `collect`ing?

**Comment by operdeck** [comment]
Yes makes sense!

Op do 3 okt 2024 om 10:30 schreef Stijn Kas ***@***.***>
